/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: eyork4633 (https://sketchfab.com/eyork4633)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/lose-the-moose-4e1afd1297e7483bbdafc0a169f86f6a
title: Lose-the-moose
*/

import React, { useEffect, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials, animations } = useGLTF("./lose-the-moose.glb");
  const { ref, actions, names } = useAnimations(animations);
  useEffect(() => {
    actions[names[0]].play();
  }, []);

  console.log("vdfvdf");
  return (
    <group ref={ref} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="DEER-Bleatfbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
            position={[0, 0, -4]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" />
                  <group name="U3DMesh" />
                  <skinnedMesh
                    name="Object_7"
                    castShadow
                    receiveShadow
                    // onClick={() => setPlay(!play)}
                    geometry={nodes.Object_7.geometry}
                    material={materials.DeerBase02_0}
                    skeleton={nodes.Object_7.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/lose-the-moose.glb");
